apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
spec:
  template:
    metadata:
      labels:
        app: my-app
    spec:
      restartPolicy: OnFailure
      containers:
      - name: my-container
        image: sagarkundral/my-python-app:v3
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: token
          readOnly: true
      volumes:
      - name: token
        projected:
          defaultMode: 420
          sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              items:
              - key: ca.crt
                path: ca.crt
              name: kube-root-ca.crt
  backoffLimit: 4
